language: node_js
node_js:
  - 14

services:
  - docker

# env:
#   global:
#     - AWS_REGION=your-aws-region
#     - AWS_ACCESS_KEY_ID=your-access-key-id
#     - AWS_SECRET_ACCESS_KEY=your-secret-access-key
#     - CLUSTER_NAME=your-eks-cluster-name

before_install:
  # Installing kubectl
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/
  
  # Install and configure AWS CLI
  - curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - aws configure set default.region ${AWS_REGION}

install:
  - npm install

script:
  # Runing Tests
  - echo "No Test to run"
  
after_success:
  # Build and push image to ECR

  - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}
  - docker build -t ${AWS_ACCOUNT}/${AWS_ECR}:${TAG} .
  - docker push ${AWS_ACCOUNT}/${AWS_ECR}:${TAG}

# deploy:
#   provider: script
#   script: ./deploy.sh
#   on:
#     branch: main
